/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_project;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hactastic
 */
public class Customer_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Form
     */
    public Customer_Frame() {
        initComponents();
        Show_Products_In_JTable();

        
    }
    
    String ImgPath = null;
    int pos = 0;
    
    public Connection getConnection()
    {
        Connection con = null ;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/products_db", "root","");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(Customer_Frame.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
    
    public ImageIcon ResizeImage(String imagePath, byte[] pic)
    {
        ImageIcon myImage = null;
        if(imagePath != null)
        {
            myImage = new ImageIcon(imagePath);
        }else{
            myImage = new ImageIcon(pic);
        }
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(ctlbl_image.getWidth(),ctlbl_image.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
    
    public ArrayList<Product> getProductList()
    {
        ArrayList<Product> productList = new ArrayList<Product>();
        Connection con = getConnection();
        String query = "SELECT * FROM products" ;
        
        Statement st;
        ResultSet rs;
        
        try {
            st = con.createStatement();
            rs = st.executeQuery(query);
            Product product;
            while(rs.next())
            {
                 product = new Product(rs.getInt("id"),rs.getString("name"),Float.parseFloat(rs.getString("price")),rs.getBytes("image"));
                productList.add(product);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Customer_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return productList;
    }
     public void Show_Products_In_JTable()
    {
        ArrayList<Product> list = getProductList();
        DefaultTableModel model = (DefaultTableModel)ctJTable_Products.getModel();
        
        model.setRowCount(0);
        Object[] row = new Object[4];
        for(int i = 0; i<list.size(); i++)
        {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getName();
            row[2] = list.get(i).getPrice();
            row[3] = list.get(i).getImage();
            
            model.addRow(row);
        
        }
    }
    
    public void ShowItem(int index)
    {
        cttxt_id.setText(Integer.toString(getProductList().get(index).getId()));
        cttxt_name.setText(getProductList().get(index).getName());
        cttxt_price.setText(Float.toString(getProductList().get(index).getPrice()));
        ctlbl_image.setIcon(ResizeImage(null,getProductList().get(index).getImage()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ctJTable_Products = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cttxt_id = new javax.swing.JTextField();
        cttxt_name = new javax.swing.JTextField();
        cttxt_price = new javax.swing.JTextField();
        ctlbl_image = new javax.swing.JLabel();
        ctbtn_first = new javax.swing.JButton();
        ctbtn_previous = new javax.swing.JButton();
        ctbtn_next = new javax.swing.JButton();
        ctbtn_last = new javax.swing.JButton();
        ctbtn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        ctJTable_Products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Image"
            }
        ));
        ctJTable_Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctJTable_ProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ctJTable_Products);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(391, 30, 452, 402);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(135, 30, 19, 38);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(109, 79, 45, 38);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Price");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(112, 128, 37, 38);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Image");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(104, 227, 50, 38);

        cttxt_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cttxt_id.setEnabled(false);
        cttxt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cttxt_idActionPerformed(evt);
            }
        });
        jPanel1.add(cttxt_id);
        cttxt_id.setBounds(172, 35, 81, 28);

        cttxt_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(cttxt_name);
        cttxt_name.setBounds(172, 84, 117, 28);

        cttxt_price.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(cttxt_price);
        cttxt_price.setBounds(172, 133, 107, 28);

        ctlbl_image.setBackground(new java.awt.Color(51, 255, 204));
        ctlbl_image.setOpaque(true);
        jPanel1.add(ctlbl_image);
        ctlbl_image.setBounds(172, 215, 191, 176);

        ctbtn_first.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store images/first.png"))); // NOI18N
        ctbtn_first.setText("First");
        ctbtn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctbtn_firstActionPerformed(evt);
            }
        });
        jPanel1.add(ctbtn_first);
        ctbtn_first.setBounds(104, 475, 106, 42);

        ctbtn_previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store images/previous.jpg"))); // NOI18N
        ctbtn_previous.setText("Previous");
        ctbtn_previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctbtn_previousActionPerformed(evt);
            }
        });
        jPanel1.add(ctbtn_previous);
        ctbtn_previous.setBounds(228, 475, 113, 42);

        ctbtn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store images/next.jpg"))); // NOI18N
        ctbtn_next.setText("Next");
        ctbtn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctbtn_nextActionPerformed(evt);
            }
        });
        jPanel1.add(ctbtn_next);
        ctbtn_next.setBounds(359, 475, 106, 42);

        ctbtn_last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store images/last.png"))); // NOI18N
        ctbtn_last.setText("Last");
        ctbtn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctbtn_lastActionPerformed(evt);
            }
        });
        jPanel1.add(ctbtn_last);
        ctbtn_last.setBounds(483, 475, 105, 42);

        ctbtn_logout.setText("Log Out");
        ctbtn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctbtn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(ctbtn_logout);
        ctbtn_logout.setBounds(640, 470, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cttxt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cttxt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cttxt_idActionPerformed

    private void ctbtn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctbtn_lastActionPerformed
        pos = getProductList().size()-1;
        ShowItem(pos);
    }//GEN-LAST:event_ctbtn_lastActionPerformed

    private void ctbtn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctbtn_firstActionPerformed
       
        pos = 0;
        ShowItem(pos);
        
    }//GEN-LAST:event_ctbtn_firstActionPerformed

    private void ctJTable_ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctJTable_ProductsMouseClicked
      
        int index = ctJTable_Products.getSelectedRow();
        ShowItem(index);
        
    }//GEN-LAST:event_ctJTable_ProductsMouseClicked

    private void ctbtn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctbtn_previousActionPerformed
        pos = pos - 1;
        
        if(pos<0)
        {
            pos = 0;
        }
        ShowItem(pos);
    }//GEN-LAST:event_ctbtn_previousActionPerformed

    private void ctbtn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctbtn_nextActionPerformed
        pos = pos + 1;
        
        if(pos >= getProductList().size())
        {
            pos = getProductList().size()-1;
        }
        ShowItem(pos);
    }//GEN-LAST:event_ctbtn_nextActionPerformed

    private void ctbtn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctbtn_logoutActionPerformed
       
        Login_Frame cust = new Login_Frame();
        this.dispose();
       cust.setVisible(true);
    }//GEN-LAST:event_ctbtn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ctJTable_Products;
    private javax.swing.JButton ctbtn_first;
    private javax.swing.JButton ctbtn_last;
    private javax.swing.JButton ctbtn_logout;
    private javax.swing.JButton ctbtn_next;
    private javax.swing.JButton ctbtn_previous;
    private javax.swing.JLabel ctlbl_image;
    private javax.swing.JTextField cttxt_id;
    private javax.swing.JTextField cttxt_name;
    private javax.swing.JTextField cttxt_price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
