/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hactastic
 */
public class SignUp_Frame extends javax.swing.JFrame {

    /**
     * Creates new form SignUp_Frame
     */
    public SignUp_Frame() {
        initComponents();
    }

    public Connection getConnection()
    {
        Connection con = null;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/products_db", "root","");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(SignUp_Frame.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
    
    public boolean signup_checkInput()
    {
        String ps1 = new String();
        String ps2 = new String();
        ps1 = sutxt_pass.getText();
        ps2 = sutxt_copass.getText();
        int compareTo = ps1.compareTo(ps2);
        
                
        if( sutxt_name.getText() == null
                || sutxt_userid.getText() == null
                || compareTo == 1
                )
        {
            return false;
        }
        else
        {
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sutxt_name = new javax.swing.JTextField();
        sutxt_userid = new javax.swing.JTextField();
        sutxt_pass = new javax.swing.JTextField();
        sutxt_copass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        subtn_signup = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cobox_UserType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 120, 50, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("User Id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 170, 60, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 220, 70, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Confirm Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 270, 130, 40);
        jPanel1.add(sutxt_name);
        sutxt_name.setBounds(470, 130, 130, 30);
        jPanel1.add(sutxt_userid);
        sutxt_userid.setBounds(470, 180, 130, 30);

        sutxt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sutxt_passActionPerformed(evt);
            }
        });
        jPanel1.add(sutxt_pass);
        sutxt_pass.setBounds(470, 230, 130, 30);
        jPanel1.add(sutxt_copass);
        sutxt_copass.setBounds(470, 280, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Fill in all the details to signup");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 50, 310, 22);

        subtn_signup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        subtn_signup.setText("Sign Up");
        subtn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtn_signupActionPerformed(evt);
            }
        });
        jPanel1.add(subtn_signup);
        subtn_signup.setBounds(390, 390, 110, 60);

        jButton1.setText("Click here to Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 460, 200, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("User Type");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 330, 70, 30);

        cobox_UserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a type", "Shopkeeper", "Customer" }));
        cobox_UserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobox_UserTypeActionPerformed(evt);
            }
        });
        jPanel1.add(cobox_UserType);
        cobox_UserType.setBounds(470, 330, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sutxt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sutxt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sutxt_passActionPerformed

    private void subtn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtn_signupActionPerformed
        
        if(signup_checkInput() == true)
        {
            
            try {
                Connection con = getConnection();
                PreparedStatement ps = con.prepareStatement("INSERT into Users (Name,User_Id,Password,User_Type) values (?,?,?,?)");
                ps.setString(1, sutxt_name.getText());
                ps.setString(2, sutxt_userid.getText());
                ps.setString(3, sutxt_pass.getText());
                ps.setString(4, (String)cobox_UserType.getSelectedItem());
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "data");
            } catch (SQLException ex) {
                Logger.getLogger(SignUp_Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"One or More Fields are missing");
        }
        System.out.println("name :" + sutxt_name.getText());
        System.out.println("userid :" + sutxt_userid.getText());
        System.out.println("password :" + sutxt_pass.getText());
        System.out.println("confirm password :" + sutxt_copass.getText());
    }//GEN-LAST:event_subtn_signupActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
        Login_Frame lf = new Login_Frame();
        lf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cobox_UserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobox_UserTypeActionPerformed
              
        // TODO add your handling code here:
    }//GEN-LAST:event_cobox_UserTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cobox_UserType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton subtn_signup;
    private javax.swing.JTextField sutxt_copass;
    private javax.swing.JTextField sutxt_name;
    private javax.swing.JTextField sutxt_pass;
    private javax.swing.JTextField sutxt_userid;
    // End of variables declaration//GEN-END:variables

    
}
